#!/usr/bin/env python3
import json
import re
from pathlib import Path

MAX_LINE_CHARS = 42
MAX_LINES = 2
MAX_CUE_CHARS = MAX_LINE_CHARS * MAX_LINES
MAX_CUE_DURATION = 7.0
MIN_CUE_DURATION = 1.0
SENTENCE_END = re.compile(r"[.!?][\"'\u2019\u201d)]?$")
MEANINGFUL = re.compile(r"[A-Za-z0-9]")


class Glossary:
    def __init__(self, prompt="", replacements=None):
        self.prompt = prompt
        self.replacements = [
            (re.compile(pattern, re.IGNORECASE), replacement)
            for pattern, replacement in (replacements or [])
        ]

    def apply(self, text):
        for pattern, replacement in self.replacements:
            text = pattern.sub(lambda match, value=replacement: value, text)
        return re.sub(r"\s+", " ", text).strip()


def load_glossary(path):
    path = Path(path)
    if not path.exists():
        return Glossary()
    data = json.loads(path.read_text(encoding="utf-8"))
    return Glossary(data.get("prompt", ""), data.get("replacements", []))


def transcribe(audio_path, model_name="distil-large-v3", device="cpu",
               compute_type="int8", model_dir=None, language="en",
               initial_prompt=None, on_progress=None):
    from faster_whisper import WhisperModel

    model = WhisperModel(
        model_name,
        device=device,
        compute_type=compute_type,
        download_root=str(model_dir) if model_dir else None,
    )
    segments, _info = model.transcribe(
        str(audio_path),
        language=language or None,
        beam_size=5,
        word_timestamps=True,
        vad_filter=True,
        vad_parameters={"min_silence_duration_ms": 300},
        initial_prompt=initial_prompt or None,
        condition_on_previous_text=False,
    )

    results = []
    for segment in segments:
        if segment.no_speech_prob > 0.8 and segment.avg_logprob < -1.0:
            continue
        words = [
            {"word": word.word.strip(), "raw": word.word, "start": word.start, "end": word.end}
            for word in (segment.words or [])
            if MEANINGFUL.search(word.word)
        ]
        text = segment.text.strip()
        if not text and not words:
            continue
        results.append({
            "start": segment.start,
            "end": segment.end,
            "text": text,
            "words": words,
        })
        if on_progress:
            on_progress(segment.end)
    return results


def build_cues(segments, glossary=None):
    words = []
    for segment in segments:
        words.extend(segment.get("words") or _even_words(segment))

    cues = []
    current = []
    for word in words:
        if current:
            chars = sum(len(item["word"]) + 1 for item in current)
            too_long = chars + len(word["word"]) > MAX_CUE_CHARS
            too_slow = word["end"] - current[0]["start"] > MAX_CUE_DURATION
            if too_long or too_slow:
                cues.append(_make_cue(current))
                current = []
        current.append(word)
        chars = sum(len(item["word"]) + 1 for item in current)
        if SENTENCE_END.search(word["word"]) and chars >= 20:
            cues.append(_make_cue(current))
            current = []
    if current:
        cues.append(_make_cue(current))

    if glossary:
        for cue in cues:
            cue["text"] = glossary.apply(cue["text"])
    cues = [cue for cue in cues if cue["text"]]
    return _merge_short(cues)


def wrap_text(text, max_chars=MAX_LINE_CHARS, max_lines=MAX_LINES):
    words = text.split()
    lines = []
    current = ""
    for word in words:
        candidate = f"{current} {word}".strip()
        if current and len(candidate) > max_chars:
            lines.append(current)
            current = word
        else:
            current = candidate
    if current:
        lines.append(current)
    while len(lines) > max_lines:
        lines[-2] = f"{lines[-2]} {lines[-1]}"
        lines.pop()
    return lines


ASS_TEMPLATE = """[Script Info]
; Generated by BD-YT-Grabber
ScriptType: v4.00+
PlayResX: {width}
PlayResY: {height}
ScaledBorderAndShadow: yes
WrapStyle: 0

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,{font},{font_size},&H00FFFFFF,&H000000FF,&H00000000,&H80000000,0,0,0,0,100,100,0,0,1,{outline},{shadow},2,{margin_h},{margin_h},{margin_v},1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""


def write_ass(cues, path, width=1920, height=1080, font="Roboto", font_size=None):
    font_size = font_size or max(24, round(height * 0.05))
    outline = max(1.0, round(font_size * 0.05, 1))
    shadow = max(0.5, round(font_size * 0.025, 1))
    margin_h = max(20, round(width * 0.05))
    margin_v = max(20, round(height * 0.055))

    lines = [ASS_TEMPLATE.format(
        width=width,
        height=height,
        font=font,
        font_size=font_size,
        outline=outline,
        shadow=shadow,
        margin_h=margin_h,
        margin_v=margin_v,
    )]
    for cue in cues:
        text = "\\N".join(wrap_text(cue["text"]))
        text = text.replace("{", "(").replace("}", ")")
        lines.append(
            f"Dialogue: 0,{_ass_time(cue['start'])},{_ass_time(cue['end'])},"
            f"Default,,0,0,0,,{text}"
        )
    Path(path).write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def write_srt(cues, path):
    blocks = []
    for index, cue in enumerate(cues, start=1):
        blocks.append(
            f"{index}\n{_srt_time(cue['start'])} --> {_srt_time(cue['end'])}\n"
            f"{cue['text']}\n"
        )
    Path(path).write_text("\n".join(blocks), encoding="utf-8")
    return path


def _join_words(words):
    text = ""
    for word in words:
        raw = word.get("raw", word["word"])
        if not text:
            text = word["word"]
        elif raw[:1].isspace():
            text += f" {word['word']}"
        else:
            text += word["word"]
    return text


def _make_cue(words):
    return {
        "start": words[0]["start"],
        "end": words[-1]["end"],
        "text": _join_words(words),
    }


def _even_words(segment):
    tokens = segment["text"].split()
    if not tokens:
        return []
    total = sum(len(token) + 1 for token in tokens)
    span = max(0.001, segment["end"] - segment["start"])
    words = []
    cursor = segment["start"]
    for token in tokens:
        duration = span * (len(token) + 1) / total
        words.append({
            "word": token,
            "raw": f" {token}" if words else token,
            "start": cursor,
            "end": min(segment["end"], cursor + duration),
        })
        cursor += duration
    return words


def _merge_short(cues):
    merged = []
    for cue in cues:
        if (merged
                and cue["end"] - cue["start"] < MIN_CUE_DURATION
                and len(merged[-1]["text"]) + len(cue["text"]) + 1 <= MAX_CUE_CHARS
                and cue["start"] - merged[-1]["end"] < 1.0):
            merged[-1]["end"] = cue["end"]
            merged[-1]["text"] = f"{merged[-1]['text']} {cue['text']}".strip()
        else:
            merged.append(dict(cue))
    for index, cue in enumerate(merged):
        if cue["end"] - cue["start"] < MIN_CUE_DURATION:
            cue["end"] = cue["start"] + MIN_CUE_DURATION
        if index + 1 < len(merged) and cue["end"] > merged[index + 1]["start"] - 0.01:
            cue["end"] = max(cue["start"] + 0.3, merged[index + 1]["start"] - 0.01)
    return merged


def _ass_time(seconds):
    centiseconds = int(round(seconds * 100))
    hours, remainder = divmod(centiseconds, 360000)
    minutes, remainder = divmod(remainder, 6000)
    secs, centiseconds = divmod(remainder, 100)
    return f"{hours}:{minutes:02d}:{secs:02d}.{centiseconds:02d}"


def _srt_time(seconds):
    milliseconds = int(round(seconds * 1000))
    hours, remainder = divmod(milliseconds, 3600000)
    minutes, remainder = divmod(remainder, 60000)
    secs, milliseconds = divmod(remainder, 1000)
    return f"{hours:02d}:{minutes:02d}:{secs:02d},{milliseconds:03d}"
